version_control:
    type: "git | svn"
    url: "git | svn repo"
    branch: "" # Optional only used for git, default is master

install:
    dir: "directory to install site into"

webserver:
    type: "nginx | apache"
    servername: "domain name for site"

dependency_manager:
    type: "composer"

database:
    type: "postgresql | mysql"
    name: "db name"
    username: "db user"
    password: "db password"

hooks:
    after_git: "shell cmd" # After all git commands have been run
    after_nginx: "shell cmd" # After nginx has parsed conf and before server reload
    after_apache: "shell cmd" # After apache has parsed conf and before server reload
    after_deploy: ["shell cmd", "shell cmd"] # After deploymenr has finished
    after_composer: "shell cmd" # After composer has run
    after_git_rollback: "shell cmd"
    after_nginx_rollback: "shell cmd"
    after_apache_rollback: "shell cmd"
    after_rollback: "shell cmd"
    after_composer_rollback: "shell cmd"
