global:
    install_dir: /var/www/test_sites/test

setup:
    tasks:
        git:
            repo: git@github.com:test.git
            tmp_dir: /tmp/deployments
        postgres:
            database: test
            username: test
            password: test
            host: localhost
        nginx:
            server_name: test.example.com
            error_log: /var/log/sitelogs/test/nginx.error.log
            access_log: /var/log/sitelogs/test/nginx.access.log

update:
    tasks:
        git:
            repo: git@github.com.com:test.git
            tmp_dir: /tmp/deployments

rollback-update:
    tasks:
        git:
            repo: git@github.com:test.git
            tmp_dir: /tmp/deployments

rollback-setup:
    tasks:
        git:
            repo: git@github.com:test.git
            tmp_dir: /tmp/deployments
        postgres:
            database: test
            username: test
            password: test
            host: localhost
        nginx:
            server_name: test.example.com
            error_log: /var/log/sitelogs/test/nginx.error.log
            access_log: /var/log/sitelogs/test/nginx.access.log
